#server port
server:
  port: 7000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethod:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            maxAge: 3600
      httpclient:
        connectTimeout: 10000
        responseTimeout: 10s
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/products/**
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/orders
  #security
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: http://localhost:8180/auth/realms/shopping-ms-realm
        registration:
          springCloudGatewayClient:
            clientId: shopping-ms-gateway-client
            clientSecret: 745cf945-1191-438c-80b2-c6b10e9b6141
            provider: keycloak
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:7000/login/oauth2/code/shopping-ms-gateway-client
#eureka
eureka: 
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7020/eureka/
#actuator
management: 
  endpoints: 
    web:
      exposure:
        include: '*'