#server port
server:
  port: 7000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethod:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            maxAge: 3600
      httpclient:
        connectTimeout: 6000
        responseTimeout: 10s
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/products/**
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/orders
#eureka
eureka: 
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7020/eureka/
#actuator
management: 
  endpoints: 
    web:
      exposure:
        include: '*'