test:
  order:
    name: ORDER
#server port
server:
  port: 0
spring:
  #rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  #datasource and jpa
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate: 
      ddlAuto: update
    showSql: true
  sql:
    init:
      mode: always
#eureka
eureka: 
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7020/eureka/

#actuator
management: 
  endpoints: 
    web:
      exposure:
        include: '*'

