test:
  product:
    name: product1
#server port
server:
  port: 0
spring:
  #rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  #security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://localhost:8180/auth/realms/shopping-ms-realm
#eureka
eureka: 
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7020/eureka/
#actuator
management: 
  endpoints: 
    web:
      exposure:
        include: '*'